on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 步骤名称
        uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: 16 # node版本
          cache: "yarn"
      - name: install
        run: yarn install
      - name: build
        run: node start.js # 此处是你node项目的构建脚本
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "main"
